#' Prepare Wien rainfall and ET0 time series for SWMM import
#'
#' Reads the rain and ET0 CSVs shipped with `kwb.raindrop` under
#' `inst/extdata/models/wien/` and writes two SWMM-5-compatible
#' time-series files:
#'
#'   * `wien_rain.dat` — 10-minute rainfall, mm per interval, suitable
#'      for a SWMM `[RAINGAGES]` entry of type VOLUME.
#'   * `wien_et0.dat`  — daily reference evapotranspiration (ET0),
#'      mm/day, suitable for the SWMM `[EVAPORATION]` block via
#'      `TIMESERIES <name>`.
#'
#' Both files follow the SWMM "external time series" format
#' (`MM/DD/YYYY HH:MM value`, blank-separated, ASCII) and can be wired
#' into a `[TIMESERIES]` entry with:
#'
#' ```
#' [TIMESERIES]
#' ;Name        Date/Time              Value
#' Wien_Rain    FILE "wien_rain.dat"
#' Wien_ET0     FILE "wien_et0.dat"
#'
#' [RAINGAGES]
#' Wien_RG VOLUME 0:10 1.0 TIMESERIES Wien_Rain
#'
#' [EVAPORATION]
#' TIMESERIES Wien_ET0
#' ```
#'
#' Usage (R):
#' ```
#' source(system.file("extdata/scripts/prepare_wien_swmm_timeseries.R",
#'                    package = "kwb.raindrop"))
#' export_wien_swmm_timeseries(out_dir = "C:/swmm/wien")
#' ```
#'
#' Source for both series: GeoSphere Austria (Österreichischer
#' Wetterdienst, formerly ZAMG), station 5925 Wien, period 2011-2025.

export_wien_swmm_timeseries <- function(
    out_dir   = tempdir(),
    path_rain = system.file("extdata/models/wien/rain.csv.gz",
                            package = "kwb.raindrop"),
    path_et   = system.file("extdata/models/wien/et.csv",
                            package = "kwb.raindrop")
) {
  stopifnot(
    nzchar(path_rain), file.exists(path_rain),
    nzchar(path_et),   file.exists(path_et)
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  # ---- Rainfall (10-minute totals, mm) ------------------------------------
  rain <- utils::read.csv(path_rain, stringsAsFactors = FALSE)
  rain$datetime <- as.POSIXct(rain$time, format = "%Y-%m-%dT%H:%M%z",
                              tz = "UTC")
  rain <- rain[!is.na(rain$datetime) & !is.na(rain$rr), ]
  rain <- rain[order(rain$datetime), ]

  rain_lines <- c(
    "; SWMM 5 external rainfall time series",
    "; Station: Wien (GeoSphere Austria, ID 5925)",
    sprintf("; Period:  %s - %s",
            format(min(rain$datetime), "%Y-%m-%d"),
            format(max(rain$datetime), "%Y-%m-%d")),
    "; Units:   mm per 10-minute interval (VOLUME)",
    "; Format:  MM/DD/YYYY  HH:MM  value",
    "; Generated by inst/extdata/scripts/prepare_wien_swmm_timeseries.R",
    sprintf("%s  %.3f",
            format(rain$datetime, "%m/%d/%Y  %H:%M"),
            rain$rr)
  )
  rain_out <- file.path(out_dir, "wien_rain.dat")
  writeLines(rain_lines, rain_out)

  # ---- Evapotranspiration (daily ET0, mm/day) -----------------------------
  et <- utils::read.csv2(path_et, dec = ".", stringsAsFactors = FALSE)
  et$date <- as.Date(et$date, format = "%d.%m.%Y")
  et <- et[!is.na(et$date) & !is.na(et$value), ]
  et <- et[order(et$date), ]

  et_lines <- c(
    "; SWMM 5 external ET0 time series",
    "; Station: Wien (GeoSphere Austria, ID 5925)",
    sprintf("; Period:  %s - %s",
            format(min(et$date), "%Y-%m-%d"),
            format(max(et$date), "%Y-%m-%d")),
    "; Units:   mm/day (reference evapotranspiration ET0)",
    "; Format:  MM/DD/YYYY  HH:MM  value   (HH:MM fixed at 00:00)",
    "; Generated by inst/extdata/scripts/prepare_wien_swmm_timeseries.R",
    sprintf("%s  00:00  %.3f",
            format(et$date, "%m/%d/%Y"),
            et$value)
  )
  et_out <- file.path(out_dir, "wien_et0.dat")
  writeLines(et_lines, et_out)

  message("SWMM time-series files written:\n",
          "  rainfall (", nrow(rain), " rows): ", rain_out, "\n",
          "  ET0      (", nrow(et),   " rows): ", et_out)
  invisible(list(rain = rain_out, et = et_out))
}

# When sourced interactively (Rscript / source()) without function
# call, do nothing — the user invokes export_wien_swmm_timeseries()
# explicitly. When run via `Rscript prepare_wien_swmm_timeseries.R
# <out_dir>`, treat the first CLI arg as out_dir.
if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  out_dir <- if (length(args) >= 1L) args[[1L]] else tempdir()
  export_wien_swmm_timeseries(out_dir = out_dir)
}
